// GENERATED by ./story_prompt.py export. Do not edit: change story/scenes/*.md or story/playlist.md.
#pragma once

enum CsMood { CS_WONDER, CS_DREAD, CS_TENSE, CS_CONFRONT, CS_SORROW, CS_HOPE, CS_MOOD_COUNT };
struct CsRect { float x, y, w, h; };                 // percent of the stage
struct CsPanel { const char *file; CsRect land, port; };
struct CsLine { const char *speaker; const char *text; int reveal; CsMood mood; };  // reveal 0 = none
struct CsScene { const char *id; const char *title; bool narration;
                 const CsPanel *panels; int panel_count; const CsLine *lines; int line_count; };

static const CsLine CS_p01_prologue_LINES[] = {
    { "Narrator", "Long ago, the people of the hills built their halls downward, toward something that sang to them in the dark.", 0, CS_WONDER },
    { "Narrator", "They grew wise there. They grew rich. And then, in a single season, they sealed every door from the inside.", 0, CS_WONDER },
    { "Narrator", "No one came out. The guards who held those doors swore an oath that outlasted their lives.", 0, CS_DREAD },
    { "Narrator", "A thousand years later, a contract appeared on a frontier quest board. Clear the entrance. Ask no questions.", 0, CS_DREAD },
    { "Narrator", "Four hunters signed it. Two of them reached the first door ahead of the others.", 0, CS_TENSE },
};

static const CsPanel CS_003_the_warning_PANELS[] = {
    { "003_the_warning_p1_establishing_wide.png", {4.0f, 5.0f, 52.0f, 36.6f}, {3.0f, 2.0f, 80.0f, 28.1f} },
    { "003_the_warning_p2_low_angle_menace.png", {73.0f, 1.0f, 22.0f, 73.8f}, {61.0f, 10.0f, 36.0f, 60.3f} },
    { "003_the_warning_p3_two_shot.png", {20.0f, 28.8f, 52.0f, 45.2f}, {17.0f, 52.0f, 80.0f, 34.8f} },
    { "003_the_warning_p4_portrait_inset.png", {65.0f, 40.6f, 17.0f, 33.4f}, {69.0f, 69.5f, 30.0f, 29.5f} },
};
static const CsLine CS_003_the_warning_LINES[] = {
    { "Bron", "It's blocking the way.", 1, CS_TENSE },
    { "Lyra", "No. Look at it. It's pointing us back.", 2, CS_DREAD },
    { "Bron", "Then it can point while I walk through it.", 3, CS_CONFRONT },
    { "Lyra", "Bron, wait.", 3, CS_CONFRONT },
    { "Lyra", "It isn't guarding the door from us. It's still guarding us from the door.", 4, CS_SORROW },
};

static const CsScene CS_INTRO[] = {
    { "p01_prologue", "Beneath the Hills", true, nullptr, 0, CS_p01_prologue_LINES, 5 },
    { "003_the_warning", "The Warning", false, CS_003_the_warning_PANELS, 4, CS_003_the_warning_LINES, 5 },
};
static const int CS_INTRO_COUNT = sizeof(CS_INTRO) / sizeof(CS_INTRO[0]);
