// GENERATED by ./story_prompt.py export. Do not edit: change story/field/text.md.
#pragma once

// What the world says when you look at it. A map's `message` trigger names an id; the
// engine looks it up here. Sorted by id, so a binary search is safe.
struct FieldText { const char *id; const char *text; };
static const FieldText FIELD_TEXT[] = {
    { "halm.guild_hall_door", "[halm.guild_hall_door: TODO]" },
    { "halm.well", "[halm.well: TODO]" },
    { "hart_yard.practice_posts", "[hart_yard.practice_posts: TODO]" },
};
#define FIELD_TEXT_COUNT 3
