"""`export`: story files -> src/cutscene_data.h and src/field_text.h.

The generated headers the game compiles against: scene kind, text, panel layout, reveal
order, music mood, portrait and portrait side per line; and FIELD_TEXT[] with the names
substituted. fast_reload.sh and deploy.sh both run this first, so editing a scene file and
hot reloading is the whole loop.

Must never do: let braces through — every string is detokenised — and never be edited the
other way round: cutscene_data.h is generated, never hand-written.
Public: c_str, cmd_export, export_field_text. Imports: cast, field, fieldtext, md, paths,
playlist, preview, rules, scenes, style.
"""
import re
import sys
from .cast import load_cast
from .field import TODO_RE
from .fieldtext import check_field_text, load_field_text
from .md import die
from .paths import ROOT, SCENES
from .playlist import playlist_lists
from .preview import page_layout, reveal_plan
from .rules import EXPR_IDS, MOODS, NARRATOR, SCENE_KINDS
from .scenes import backdrop_panel, panel_file, parse_scene, portrait_file, speaker_sides, validate
from .style import load_style



# ───────────────────────── Export to the game ─────────────────────────

GAME_HEADER = ROOT.parent / "src" / "cutscene_data.h"


GAME_FIELD_TEXT = ROOT.parent / "src" / "field_text.h"


def c_str(text):
    for a, b in (("‘", "'"), ("’", "'"), ("“", '"'), ("”", '"'), ("—", " - "), ("…", "...")):
        text = text.replace(a, b)
    text = text.encode("ascii", "replace").decode()              # the game font covers Basic Latin
    return '"' + text.replace("\\", "\\\\").replace('"', '\\"') + '"'


def cmd_export(args):
    style, cast = load_style(), load_cast()
    lists = playlist_lists()
    # THE GAME PLAYS CHAPTERS. New Game runs `## chapter01` from its first scene; there is no longer
    # a separate `## intro` list with a special role (D23 — the game is written one chapter at a
    # time). Every '## chapterNN' list in playlist.md is exported in order, art or no art: a panel
    # scene with nothing generated yet exports with every panel a placeholder carrying its
    # description, so the chapter always plays end to end while the sheets are being drawn.
    want = {name: [stem for stem, _ in rows] for name, rows in lists.items()
            if re.fullmatch(r"chapter\d+", name)}
    if not want:
        die("playlist.md: no '## chapterNN' list to export. The game plays chapters; add one.")
    chapter_names = sorted(want)
    stems = list(dict.fromkeys(s for n in chapter_names for s in want[n]))   # unique, in play order
    out = ["// GENERATED by ./story_prompt.py export. Do not edit: change story/scenes/*.md or story/playlist.md.",
           "#pragma once", "",
           "enum CsMood { " + ", ".join(f"CS_{m.upper()}" for m in MOODS) + ", CS_MOOD_COUNT };",
           "enum CsKind { " + ", ".join(f"CS_{k.upper()}" for k in SCENE_KINDS) + " };   // panels = manga page, "
           "narration = text over black, talk = dialogue box over black or a dimmed backdrop",
           "enum CsSide { CS_LEFT, CS_RIGHT };                   // which end of the dialogue box a portrait sits at",
           "struct CsRect { float x, y, w, h; };                 // percent of the stage",
           "struct CsPanel { const char *file; int page; CsRect land, port;   // a new page clears the screen",
           "                 const char *desc; };   // the panel's one-line description, drawn small inside the",
           "// placeholder box when file does not exist yet, so pacing can be judged before the art is generated.",
           "#define CS_HAS_PANEL_DESC 1",
           "struct CsLine { const char *speaker; const char *text; int reveal; CsMood mood;  // reveal 0 = none",
           "                const char *portrait; CsSide side;    // portrait file, or nullptr when the speaker has none",
           "                const char *expr; };                  // \"\" when untagged; else one of the ten ids below.",
           "// A tagged line's face is portrait_<name>_<expr>.png, falling back to portrait_<name>.png.",
           "// text may be \"\" on a tagged line: a reaction beat, the portrait with an empty box.",
           "#define CS_HAS_EXPR 1",
           "// " + ", ".join(EXPR_IDS),
           f'#define CS_NARRATOR "{NARRATOR.title()}"              '
           "// speaker of an unattributed box: no name drawn, never a portrait",
           "struct CsScene { const char *id; const char *title; bool narration;   // narration == (kind == CS_NARRATION)",
           "                 CsKind kind; const char *backdrop;   // backdrop: talk scenes only, may be nullptr",
           "                 const CsPanel *panels; int panel_count; const CsLine *lines; int line_count; };", ""]
    rows, mood, emitted = {}, "tense", set()
    for stem in stems:
        path = SCENES / f"{stem}.md"
        if not path.exists():
            die(f"playlist.md lists '{stem}' but {path.relative_to(ROOT.parent)} does not exist")
        scene = parse_scene(path)
        err, _ = validate(scene, style, cast)
        if err:
            for e in err:
                print(f"{path.name}: ERROR: {e}", file=sys.stderr)
            sys.exit("story_prompt: scene rejected. Fix the scene file; do not bypass the rules.")
        if not scene["dialogue"]:                               # the game advances on dialogue lines
            print(f"skipped {stem}: no dialogue lines, so the game could never advance past it", file=sys.stderr)
            continue
        missing = [panel_file(scene, n, sid).name for n, (sid, _) in enumerate(scene["panels"], 1)
                   if not panel_file(scene, n, sid).exists()]
        if scene["panels"] and len(missing) == len(scene["panels"]):
            # Exported anyway: the chapter script names this scene, and a clip that vanished would
            # break the chapter. Every panel is a placeholder box with its description in it.
            print(f"{stem}: no panel art generated yet; every panel is a placeholder", file=sys.stderr)
        elif missing:                                          # the game draws a placeholder box for these
            print(f"{stem}: {len(missing)} of {len(scene['panels'])} panels have no art yet, shown as placeholders "
                  f"({', '.join(m.split('_', 3)[-1].removesuffix('.png') for m in missing)})", file=sys.stderr)
        ident = re.sub(r"\W", "_", stem)
        if ident in emitted:                                      # a playlist may play the same scene twice
            print(f"{stem}: listed more than once; the second entry reuses the first one's tables", file=sys.stderr)
        else:
            emitted.add(ident)
            if scene["panels"]:
                land, port = page_layout(scene, style, "land"), page_layout(scene, style, "port")
                out.append(f"static const CsPanel CS_{ident}_PANELS[] = {{")
                descs = [d for _, d in scene["panels"]]
                for i, (a, b) in enumerate(zip(land, port)):
                    rect = lambda r: "{" + ", ".join(f"{float(r[k]):.1f}f" for k in "xywh") + "}"
                    out.append(f'    {{ "{a["file"]}", {a["page"]}, {rect(a)}, {rect(b)}, '
                               f'{c_str(descs[i] if i < len(descs) else "")} }},')
                out.append("};")
            sides = speaker_sides(scene, cast)                    # first speaker left, second right, then alternating
            out.append(f"static const CsLine CS_{ident}_LINES[] = {{")
            for (who, text), reveal, tag, expr in zip(scene["dialogue"], reveal_plan(scene),
                                                      scene["moods"], scene["exprs"]):
                mood = tag or mood                                # an untagged line keeps the current mood
                pf = portrait_file(who, cast)                     # an alias uses its handle's portrait
                face = c_str(f"portrait_{pf.name}") if pf else "nullptr"
                side = "CS_RIGHT" if sides[who.strip().lower()] else "CS_LEFT"
                out.append(f"    {{ {c_str(who)}, {c_str(text)}, {reveal}, CS_{mood.upper()}, {face}, "
                           f"{side}, {c_str(expr or '')} }},")
            out += ["};", ""]
        title = re.sub(r"^(Scene \S+|Prologue):\s*", "", scene["title"])
        panels = f"CS_{ident}_PANELS, {len(scene['panels'])}" if scene["panels"] else "nullptr, 0"
        bd = backdrop_panel(scene) if scene["talk"] else None
        backdrop = c_str(bd[2].name) if bd and bd[2] and bd[2].exists() else "nullptr"
        rows[stem] = (f'    {{ "{stem}", {c_str(title)}, {"true" if scene["narration"] else "false"}, '
                      f'CS_{scene["kind"].upper()}, {backdrop}, '
                      f'{panels}, CS_{ident}_LINES, {len(scene["dialogue"])} }},')
    if not rows:
        die("nothing to export: no listed scene is complete")
    for name in chapter_names:
        arr = "CS_" + name.upper()                            # chapter01 -> CS_CHAPTER01
        body = [rows[s] for s in want[name] if s in rows]
        if not body:                                          # an empty chapter list is not an error
            out += [f"static const CsScene {arr}[1] = {{}};", f"static const int {arr}_COUNT = 0;", ""]
            continue
        out += [f"static const CsScene {arr}[] = {{"] + body + ["};",
                f"static const int {arr}_COUNT = sizeof({arr}) / sizeof({arr}[0]);", ""]
    # One table over the lot, so the game walks chapters rather than naming each array. `number` is
    # the chapter's own number (chapter01 -> 1), which is what a save file stores.
    out += ["struct CsChapter { const char *id; int number; const CsScene *scenes; int count; };",
            "#define CS_HAS_CHAPTERS 1",
            "static const CsChapter CS_CHAPTERS[] = {"]
    for name in chapter_names:
        arr, number = "CS_" + name.upper(), int(name.removeprefix("chapter"))
        out.append(f'    {{ "{name}", {number}, {arr}, {arr}_COUNT }},')
    out += ["};", "static const int CS_CHAPTER_COUNT = sizeof(CS_CHAPTERS) / sizeof(CS_CHAPTERS[0]);",
            "// New Game starts at CS_CHAPTERS[0].", ""]
    GAME_HEADER.write_text("\n".join(out))
    print(f"wrote {GAME_HEADER.relative_to(ROOT.parent)}  ({len(rows)} of {len(stems)} scenes)")
    export_field_text()


def export_field_text():
    """story/field/text.md -> src/field_text.h: the examine lines, names substituted, sorted by id."""
    err, _ = check_field_text()
    if err:
        for e in err:
            print(f"ERROR: {e}", file=sys.stderr)
        sys.exit("story_prompt: field text rejected. Fix story/field/text.md; do not bypass the rules.")
    entries = load_field_text()
    out = ["// GENERATED by ./story_prompt.py export. Do not edit: change story/field/text.md.",
           "#pragma once", "",
           "// What the world says when you look at it. A map's `message` trigger names an id; the",
           "// engine looks it up here. Sorted by id, so a binary search is safe.",
           "// name is the display name to draw over the box, or \"\" when the line has no speaker.",
           "struct FieldText { const char *id; const char *text; const char *name; };",
           "static const FieldText FIELD_TEXT[] = {"]
    for ident in sorted(entries):
        e = entries[ident]
        out.append(f"    {{ {c_str(ident)}, {c_str(e['text'])}, {c_str(e['name'])} }},")
    out += ["};", f"#define FIELD_TEXT_COUNT {len(entries)}", ""]
    GAME_FIELD_TEXT.write_text("\n".join(out))
    todo = sum(1 for e in entries.values() if TODO_RE.match(e["raw"]))
    print(f"wrote {GAME_FIELD_TEXT.relative_to(ROOT.parent)}  ({len(entries)} line(s)"
          + (f", {todo} still a placeholder)" if todo else ")"))
