"""Where everything lives on disk, and nothing else.

Every other module asks this one for a directory. It is the bottom of the import graph:
it imports the standard library only, so a path may never be computed from a rule, a
scene or a name table. ROOT is story/ inside REPO, which is this package's parent — if
storytool/ ever moves, this is the single line that changes.

Public: REPO, ROOT, STYLE, CAST, STATE_FILES, SCENES, OUT, PANELS, PORTRAITS, SHEETS,
NAMES_FILE, FIELD and its subdirectories, expr_portrait_path().
Imports: pathlib only.
"""
from pathlib import Path



REPO = Path(__file__).resolve().parent.parent   # the checkout; storytool/ sits in it
ROOT = REPO / "story"


STYLE, CAST = ROOT / "STYLE.md", ROOT / "characters.md"


# The story state used to be one story/plot.md. Under D23 the chapter is written as a whole,
# so the state a scene writer needs is the live chapter file plus the open threads.
STATE_FILES = (ROOT / "v3" / "THREADS.md", ROOT / "v3" / "BRAINSTORM.md")


SCENES, OUT, PANELS = ROOT / "scenes", ROOT / "out", ROOT / "panels"


PORTRAITS = ROOT / "portraits"                      # generated by `portraits` from story/refs/


SHEETS = ROOT / "sheets"                            # every raw generation, kept so a sheet can be re-cut


FIELD = ROOT / "field"


FIELD_DIRS = {"walker": FIELD / "walkers", "sprite": FIELD / "sprites"}


FIELD_DOCS = {"walker": FIELD / "walkers.md", "sprite": FIELD / "sprites.md"}


FIELD_MANIFEST = FIELD / "manifest.md"


FIELD_TEXT = FIELD / "text.md"        # examine text: '## <map>.<id>' -> one or two sentences


def expr_portrait_path(key, expr):
    return PORTRAITS / f"{key}_{expr}.png"
